server:
    port: 5000
spring: 
    datasource: 
        url: jdbc:sqlserver://165.22.121.230;database=GreenHouseDB
        username: sa
        password: j8ugY6-c42zer
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        show-sql: true
        # database-platform: org.hibernate.dialect.SQLServer2012Dialect
        # hibernate:
        #     ddl-auto: none
springdoc:
    swagger-ui: 
        path: /
        operationsSorter: method
